server {
    listen 80 default_server;
    server_name _;
    server_tokens off;
    client_max_body_size 1k;
    location / {
        limit_except GET HEAD { deny all; }
        proxy_pass http://127.0.0.1:8001;
        proxy_connect_timeout 3s;
        proxy_read_timeout 90s;
        add_header X-Content-Type-Options nosniff always;
    }
}
