"""Stage only reviewed shared Python modules; never upload the checkout or runtime data."""
from pathlib import Path
import hashlib
import json
import shutil

ROOT = Path(__file__).resolve().parents[1]
STAGE = ROOT / "cloudflare/src/ledger"
STAGE.mkdir(parents=True, exist_ok=True)
MODULES = ("__init__.py", "metar.py", "policy.py", "evidence.py", "sources.py")
for name in MODULES:
    shutil.copyfile(ROOT / "ledger" / name, STAGE / name)
config = {name: json.loads((ROOT / "config" / f"{name}.json").read_text())
          for name in ("airports", "policy", "sources", "retention")}
config["legacy_policy"] = json.loads((ROOT / "config/policies/routine-metar-v2.json").read_text())
files = [*(ROOT / "ledger").glob("*.py"), *(ROOT / "cloudflare/src").glob("*.py")]
config["engine_hashes"] = {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                           for p in sorted(files) if p.name != "settings.py"}
(ROOT / "cloudflare/src/settings.py").write_text(
    '# Generated by scripts/prepare_cloudflare.py; review config/*.json instead.\n'
    + "SETTINGS = " + repr(config) + "\n")
print("Staged shared parser, selection policy, source decoders, and reviewed configuration.")
